on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build and deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          local_path: '.'
          remote_path: '/opt/ardeco/support'
          sftp_only: true
